name: pre-commit

on:
  pull_request:
    branches: ['*']
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: "install project dependencies"
      run : |
        python -m pip install --upgrade pip
        pip install setuptools_scm wheel
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - uses: pre-commit/action@v3.0.0
