name: UnitTestExecution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]
    name: Testing on python version - ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Run unit test cases
        run: coverage run --source=src.pg_bulk_loader --module pytest --verbose  && coverage report --show-missing
